services:
  ingress:
    image: cenk1cenk2/nginx-ingress:test
    build:
      context: .
    environment:
      LOG_LEVEL: trace
      NGINX_INGRESS: |
        [
          {
            "server": {
              "listen": "80",
              "options": {
                "# test": "test",
                "# test2": "test"
              }
            },
            "upstream": {
              "servers": [
                "balance-1:80",
                "balance-2:80"
              ],
              "options": {
                "least_conn": null,
                "# test": "test"
              }
            }
          }
        ]
    ports:
      - 80:80

  balance-1:
    image: nginx:alpine
    logging:
      driver: "none"

  balance-2:
    image: nginx:alpine
    logging:
      driver: "none"
